//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Search.g4 by ANTLR 4.7

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="SearchParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7")]
[System.CLSCompliant(false)]
public interface ISearchListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="SearchParser.searchUnit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSearchUnit([NotNull] SearchParser.SearchUnitContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SearchParser.searchUnit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSearchUnit([NotNull] SearchParser.SearchUnitContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SearchParser.defaultOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDefaultOp([NotNull] SearchParser.DefaultOpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SearchParser.defaultOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDefaultOp([NotNull] SearchParser.DefaultOpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SearchParser.exactText"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExactText([NotNull] SearchParser.ExactTextContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SearchParser.exactText"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExactText([NotNull] SearchParser.ExactTextContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SearchParser.hashText"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHashText([NotNull] SearchParser.HashTextContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SearchParser.hashText"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHashText([NotNull] SearchParser.HashTextContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SearchParser.toText"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterToText([NotNull] SearchParser.ToTextContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SearchParser.toText"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitToText([NotNull] SearchParser.ToTextContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SearchParser.fromText"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFromText([NotNull] SearchParser.FromTextContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SearchParser.fromText"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFromText([NotNull] SearchParser.FromTextContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SearchParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTerm([NotNull] SearchParser.TermContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SearchParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTerm([NotNull] SearchParser.TermContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SearchParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpr([NotNull] SearchParser.ExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SearchParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpr([NotNull] SearchParser.ExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SearchParser.op"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOp([NotNull] SearchParser.OpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SearchParser.op"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOp([NotNull] SearchParser.OpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SearchParser.word"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWord([NotNull] SearchParser.WordContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SearchParser.word"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWord([NotNull] SearchParser.WordContext context);
}
