//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Search.g4 by ANTLR 4.7

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="ISearchListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7")]
[System.CLSCompliant(false)]
public partial class SearchBaseListener : ISearchListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="SearchParser.searchUnit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSearchUnit([NotNull] SearchParser.SearchUnitContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SearchParser.searchUnit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSearchUnit([NotNull] SearchParser.SearchUnitContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SearchParser.defaultOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDefaultOp([NotNull] SearchParser.DefaultOpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SearchParser.defaultOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDefaultOp([NotNull] SearchParser.DefaultOpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SearchParser.exactText"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExactText([NotNull] SearchParser.ExactTextContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SearchParser.exactText"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExactText([NotNull] SearchParser.ExactTextContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SearchParser.hashText"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHashText([NotNull] SearchParser.HashTextContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SearchParser.hashText"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHashText([NotNull] SearchParser.HashTextContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SearchParser.toText"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterToText([NotNull] SearchParser.ToTextContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SearchParser.toText"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitToText([NotNull] SearchParser.ToTextContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SearchParser.fromText"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFromText([NotNull] SearchParser.FromTextContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SearchParser.fromText"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFromText([NotNull] SearchParser.FromTextContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SearchParser.term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTerm([NotNull] SearchParser.TermContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SearchParser.term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTerm([NotNull] SearchParser.TermContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SearchParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpr([NotNull] SearchParser.ExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SearchParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpr([NotNull] SearchParser.ExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SearchParser.op"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOp([NotNull] SearchParser.OpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SearchParser.op"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOp([NotNull] SearchParser.OpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SearchParser.word"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWord([NotNull] SearchParser.WordContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SearchParser.word"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWord([NotNull] SearchParser.WordContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
